resource-pack-url: "https://drive.google.com/uc?export=download&id=1Z9SwvDNx4XPX19vh4mROcBtmFKUx8CeH"
resource-pack-sha1: "11c2e776080e18dced471522c5d1b254bbf0788b"
resource-pack-use-sha1: true
resource-pack-prompt: "WirelessHopper Resource Pack"
resource-pack-required: false
resource-pack-auto-on-join: true
lang-default: "de"
recipes-auto-unlock-on-join: true

transfer:
  default:
    cooldown-ticks: 8
    items-per-transfer: 1
  upgrades:
    iron:
      cooldown-ticks: 6
      items-per-transfer: 2
    gold:
      cooldown-ticks: 4
      items-per-transfer: 4
    diamond:
      cooldown-ticks: 2
      items-per-transfer: 8
    netherite:
      cooldown-ticks: 1
      items-per-transfer: 16
