lang-default: "de"

limits:
  max-hoppers-per-player: -1

transfer:
  default:
    cooldown-ticks: 8
    items-per-transfer: 1
  upgrades:
    iron:
      cooldown-ticks: 6
      items-per-transfer: 2
    gold:
      cooldown-ticks: 4
      items-per-transfer: 4
    diamond:
      cooldown-ticks: 2
      items-per-transfer: 8
    netherite:
      cooldown-ticks: 1
      items-per-transfer: 16
