name: WirelessHopper
version: '${version}'
main: com.hnp_arda.wireless_hoppers.Main
api-version: '1.20'
permissions:
  wirelesshopper.place:
    description: Allows placing Wireless Hoppers.
    default: true
  wirelesshopper.use:
    description: Allows using and breaking Wireless Hoppers.
    default: true
  wirelesshopper.pack:
    description: Allows prompting the resource pack.
    default: true
  wirelesshopper.give:
    description: Allows giving Wireless Hopper items.
    default: op

commands:
  wirelesshopper:
    description: Wireless Hopper commands.
    usage: /wirelesshopper give <player> <item> | /wirelesshopper pack
